# -*- encoding: utf-8 -*-
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'tim/version'
Gem::Specification.new do |gem|
  gem.name          = 'tim'
  gem.version       = '0.0.1'
  gem.authors       = ['Autogenerated From ReACG']
  gem.email         = ['autogen@reacg.org']
  gem.description   = 'autogenerated ReST Client lib'
  gem.summary       = 'autogenerated ReSt Client lib'
  gem.homepage      = 'http://www.reacg.org'
  gem.executables   = gem.files.grep(%r{^bin/}).map{ |f| File.basename(f) }
  gem.test_files    = gem.files.grep(%r{^(test|spec|features)/})
  gem.test_files    = gem.files.grep(%r{^(test|spec|features)/})
  gem.require_paths = ['lib']
end